import myheatmap as hm


#filename = "history-04-22-2014"
#filename = "history10-24-2013to06-04-2014"
filename = "history10-24-2013to07-11-14"

(date,time,lat,lon) = hm.readCSV(filename)

htmlfile = 'gHM_'+filename+'.html'

f = open(htmlfile,'w')
f.write('<!DOCTYPE html>\n')
f.write('<html>\n')
f.write('<head>\n')
f.write('<meta charset="utf-8">\n')
f.write('<title>Google Maps - heatmap </title>\n')
f.write('<style>\n')
f.write('      html, body, #map-canvas {\n')
f.write('        height: 100%;\n')
f.write('        margin: 0px;\n')
f.write('        padding: 0px\n')
f.write('      }\n')
f.write('      #panel {\n')
f.write('        position: absolute;\n')
f.write('        top: 5px;\n')
f.write('        left: 25%;\n')
f.write('        margin-left: -180px;\n')
f.write('        z-index: 5;\n')
f.write('        background-color: #fff;\n')
f.write('        padding: 5px;\n')
f.write('        border: 1px solid #999;\n')
f.write('      }\n')
f.write('    </style>\n')
f.write('    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=visualization"></script>\n')
f.write('<script>\n')
f.write('var map, pointarray, heatmap; \n')
f.write('var Data = [\n')

for i in range(len(date)):
    f.write('new google.maps.LatLng('+lat[i]+', '+lon[i]+'),\n')

f.write('];\n\n')

f.write('function initialize() {\n')
f.write('  var mapOptions = {\n')
f.write('    zoom: 11,\n')
f.write('    center: new google.maps.LatLng(37.8, -122.3),\n')
f.write('    mapTypeId: google.maps.MapTypeId.SATELLITE\n')
f.write('  };\n')
f.write('\n')
f.write('  map = new google.maps.Map(document.getElementById(\'map-canvas\'),\n')
f.write('      mapOptions);\n')
f.write('\n')
f.write('  var pointArray = new google.maps.MVCArray(Data);\n')
f.write('\n')
f.write('  heatmap = new google.maps.visualization.HeatmapLayer({\n')
f.write('    data: pointArray\n')
f.write('  });\n')
f.write('\n')
f.write('  heatmap.setMap(map);\n')
f.write('  heatmap.set(\'maxIntensity\',5);\n')
f.write('  heatmap.set(\'radius\',10);\n')
f.write('}\n')
f.write('\n')
f.write('function changeRadius() {\n')
f.write('  heatmap.set(\'radius\', 10);\n')
f.write('}\n')
f.write('\n')
f.write('function increaseRadius() {\n')
f.write('  heatmap.set(\'radius\', heatmap.get(\'radius\') ? heatmap.get(\'radius\')+1 : 1);\n')
f.write('}\n')
f.write('function decreaseRadius() {\n')
f.write('  heatmap.set(\'radius\', heatmap.get(\'radius\') ? heatmap.get(\'radius\') -1 : 0);\n')
f.write('}\n')
f.write('function changeMaxIntensity() {\n')
f.write('  heatmap.set(\'maxIntensity\', 5);\n')
f.write('}\n')
f.write('function increaseMaxIntensity() {\n')
f.write('  heatmap.set(\'maxIntensity\', heatmap.get(\'maxIntensity\') ? heatmap.get(\'maxIntensity\')+1 : 1);\n')
f.write('}\n')
f.write('function decreaseMaxIntensity() {\n')
f.write('  heatmap.set(\'maxIntensity\', heatmap.get(\'maxIntensity\')<2 ? 1 : heatmap.get(\'maxIntensity\')-1 );\n')
f.write('}\n')
f.write('function increaseMaxIntensity10() {\n')
f.write('  heatmap.set(\'maxIntensity\', heatmap.get(\'maxIntensity\') ? heatmap.get(\'maxIntensity\')+10 : 10);\n')
f.write('}\n')
f.write('function decreaseMaxIntensity10() {\n')
f.write('  heatmap.set(\'maxIntensity\', heatmap.get(\'maxIntensity\')<11 ? 1 : heatmap.get(\'maxIntensity\')-10 );\n')
f.write('}\n')
f.write('function increaseMaxIntensity100() {\n')
f.write('  heatmap.set(\'maxIntensity\', heatmap.get(\'maxIntensity\') ? heatmap.get(\'maxIntensity\')+100 : 100);\n')
f.write('}\n')
f.write('function decreaseMaxIntensity100() {\n')
f.write('  heatmap.set(\'maxIntensity\', heatmap.get(\'maxIntensity\')<101 ? 1 : heatmap.get(\'maxIntensity\')-100 );\n')
f.write('}\n')
f.write('function changeOpacity() {\n')
f.write('  heatmap.set(\'opacity\', heatmap.get(\'opacity\') ? null : 0.2);\n')
f.write('}\n')
f.write('\n')
f.write('google.maps.event.addDomListener(window, \'load\', initialize);\n')
f.write('\n')
f.write('    </script>\n')
f.write('  </head>\n')
f.write('\n')
f.write('  <body>\n')
f.write('    <div id="panel">\n')
f.write('      <button onclick="changeRadius()">rad=10</button>\n')
f.write('      <button onclick="increaseRadius()">+1rad</button>\n')
f.write('      <button onclick="decreaseRadius()">-1rad</button>\n')
f.write('      <button onclick="changeOpacity()">Change opacity</button>\n')
f.write('      <button onclick="changeMaxIntensity()">MaxIntensity=5</button>\n')
f.write('      <button onclick="increaseMaxIntensity()">+1MaxInt</button>\n')
f.write('      <button onclick="decreaseMaxIntensity()">-1MaxInt</button>\n')
f.write('      <button onclick="increaseMaxIntensity10()">+10MaxInt</button>\n')
f.write('      <button onclick="decreaseMaxIntensity10()">-10MaxInt</button>\n')
f.write('      <button onclick="increaseMaxIntensity100()">+100MaxInt</button>\n')
f.write('      <button onclick="decreaseMaxIntensity100()">-100MaxInt</button>\n')
f.write('    </div>\n')
f.write('    <div id="map-canvas"></div>\n')
f.write('  </body>\n')
f.write('</html>\n')
f.close()